# Generated by Django 5.2.17 on 2026-08-17 21:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_count', models.PositiveBigIntegerField(default=0)),
                ('write_count', models.PositiveBigIntegerField(default=0)),
                ('last_read_at', models.DateTimeField(blank=True, null=True)),
                ('last_write_at', models.DateTimeField(blank=True, null=True)),
                ('app', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='usage', to='courses.app')),
            ],
            options={
                'verbose_name': 'app usage',
                'verbose_name_plural': 'app usage',
            },
        ),
    ]
