"""Core Ldrbrd data model.

An instructor (a staff user) owns Courses.  Students join a course with the
link the instructor hands out, then register Apps inside it.  Each App gets an
autogenerated secret key; once the instructor approves the App, that key lets
the student's code write a single arbitrary JSON document.  Reading that
document is public and needs no key.
"""

import secrets

from django.conf import settings
from django.db import models
from django.utils import timezone
from django.utils.text import slugify


def generate_secret_key() -> str:
    """A URL-safe secret an app passes in its querystring on every write."""
    return secrets.token_urlsafe(32)


def generate_join_token() -> str:
    """The unguessable part of the course link an instructor shares."""
    return secrets.token_urlsafe(16)


def unique_slug(model, base: str, fallback: str, **scope) -> str:
    """Slugify ``base``, then disambiguate within ``scope`` if needed."""
    stem = slugify(base)[:90] or fallback
    slug = stem
    suffix = 2
    while model.objects.filter(slug=slug, **scope).exists():
        slug = f"{stem}-{suffix}"
        suffix += 1
    return slug


class Course(models.Model):
    owner = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name="courses",
        help_text="The staff user who created this course.",
    )
    name = models.CharField(max_length=200)
    slug = models.SlugField(max_length=100)
    description = models.TextField(blank=True)
    join_token = models.CharField(
        max_length=64, unique=True, default=generate_join_token, editable=False
    )
    is_open = models.BooleanField(
        default=True,
        help_text="When off, the join link stops accepting new students.",
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ("-created_at",)
        constraints = [
            models.UniqueConstraint(
                fields=("owner", "slug"), name="unique_course_slug_per_owner"
            )
        ]

    def __str__(self) -> str:
        return f"{self.owner.username}/{self.slug}"

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = unique_slug(
                Course, self.name, fallback="course", owner=self.owner
            )
        super().save(*args, **kwargs)

    @property
    def join_url(self) -> str:
        return f"{settings.LDRBRD_BASE_URL}/join/{self.join_token}"

    @property
    def data_url(self) -> str:
        return f"{settings.LDRBRD_BASE_URL}/{self.owner.username}/{self.slug}"

    def is_owned_by(self, user) -> bool:
        return user.is_authenticated and self.owner_id == user.id

    def is_administered_by(self, user) -> bool:
        """Course owner or a Django superuser."""
        return user.is_authenticated and (self.owner_id == user.id or user.is_superuser)


class Enrollment(models.Model):
    """Records that a student redeemed a course's join link."""

    course = models.ForeignKey(
        Course, on_delete=models.CASCADE, related_name="enrollments"
    )
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="enrollments"
    )
    joined_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ("-joined_at",)
        constraints = [
            models.UniqueConstraint(
                fields=("course", "user"), name="unique_enrollment_per_course"
            )
        ]

    def __str__(self) -> str:
        return f"{self.user.username} in {self.course}"


class App(models.Model):
    """A student-registered application that writes into a course."""

    course = models.ForeignKey(Course, on_delete=models.CASCADE, related_name="apps")
    owner = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="apps"
    )
    name = models.CharField(max_length=200)
    slug = models.SlugField(max_length=100)
    secret_key = models.CharField(
        max_length=64, default=generate_secret_key, editable=False, db_index=True
    )
    approved = models.BooleanField(
        default=False,
        help_text="Until the instructor approves it, writes are rejected.",
    )
    approved_at = models.DateTimeField(null=True, blank=True)
    approved_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="approved_apps",
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ("-created_at",)
        constraints = [
            models.UniqueConstraint(
                fields=("course", "slug"), name="unique_app_slug_per_course"
            )
        ]

    def __str__(self) -> str:
        return f"{self.course}/{self.slug}"

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = unique_slug(App, self.name, fallback="app", course=self.course)
        super().save(*args, **kwargs)

    @property
    def data_url(self) -> str:
        return f"{self.course.data_url}/{self.slug}"

    def approve(self, by_user) -> None:
        self.approved = True
        self.approved_at = timezone.now()
        self.approved_by = by_user
        self.save(update_fields=["approved", "approved_at", "approved_by", "updated_at"])

    def unapprove(self) -> None:
        self.approved = False
        self.approved_at = None
        self.approved_by = None
        self.save(update_fields=["approved", "approved_at", "approved_by", "updated_at"])

    def rotate_secret(self) -> str:
        self.secret_key = generate_secret_key()
        self.save(update_fields=["secret_key", "updated_at"])
        return self.secret_key

    def is_owned_by(self, user) -> bool:
        return user.is_authenticated and self.owner_id == user.id

    def is_administered_by(self, user) -> bool:
        """The app's own student, its course's instructor, or a superuser."""
        return user.is_authenticated and (
            self.owner_id == user.id
            or self.course.owner_id == user.id
            or user.is_superuser
        )


class AppData(models.Model):
    """The one arbitrary JSON document an app stores. World readable."""

    app = models.OneToOneField(App, on_delete=models.CASCADE, related_name="data")
    # null=True because a bare JSON `null` is a legal document and an app is
    # allowed to store one.  "Never written" is told apart from "written as
    # null" by whether an AppData row exists at all, not by this column.
    payload = models.JSONField(default=dict, blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = "app data"
        verbose_name_plural = "app data"

    def __str__(self) -> str:
        return f"data for {self.app}"
